update run_hadoop file
kmubigdata/ubuntu-hadoop pull request #12
Opened 2018-11-15 06:45 UTC by eyeballss

기존의 run_hadoop을 짧게 수정하였습니다.
피드백 부탁드립니다.

2018-11-15 21:02 UTC, kmu-leeky commented on run_hadoop
> +        echo "./run_hadoop [network-name] [want-master] [slave-from] [slave-to]"
want-master, slave-from, slave-to 가 무슨 의미인지?

2018-11-15 21:03 UTC, kmu-leeky commented on run_hadoop
> +        echo "Overlay network is my-net, 0 for creating master container but 1, slave from 1, slave to 5"
무슨 얘기인지. 잘이해가.. 한글로 작성해도 괜찮아. 해당 명령어를 실행하는게 master 와 worker 에서 다 달라야 한다는 거지?

2018-11-15 21:04 UTC, kmu-leeky commented on run_hadoop
>  numOfContainers=1
27라인에 있으니 삭제해도 될듯

2018-11-15 21:04 UTC, kmu-leeky commented on run_hadoop
>  numOfContainers=1
27라인에 있으니 삭제해도 될듯

2018-11-15 21:07 UTC, kmu-leeky commented on run_hadoop
> +MASTER_OPTION="--cpu-shares 1024 --memory 12g"
메모리를 하드 코딩 하기 보다, 각 서버에서 사용하고자 하는 메모리양, 전체 디스크양을 입력인자로 받아서 (optional 한 값으로), 해당 값들이 입력된다면 입력된 값으로, 그렇지 않을 경우에는 기본 값으로 설정 한 후에, 컨테이너 갯수 만큼 해서 나눠주는게 나을것 같아.

2018-11-15 21:08 UTC, kmu-leeky commented on run_hadoop
> +
여기서 comment 추가해주는것도 좋을듯. 아니면 코드가 이해가 쉬우려면 != 체크가 아닌 < 가 더 맞을듯

2018-11-15 21:09 UTC, hyu-leeky requested changes
Dockerfile 업데이트한건 어디에 있어?

2018-11-16 02:21 UTC, eyeballss commented on run_hadoop
> +        echo "./run_hadoop [network-name] [want-master] [slave-from] [slave-to]"
want-master 는 0일때 마스터 컨테이너를 만들고 1일때 만들지 않는 flag 입니다.
slave-from, slave-to 는 slave 만들 때의 개수입니다
예를 들어 run_hadoop my-net 0 1 4 하면
my-net 이라는 네트워크위에 마스터 컨테이너 하나와 slave1, slave2, slave3, slave4 컨테이너들을 만듭니다.

알아보기 어려우시다면^^; 쉽게 다시 만들도록 하겠습니다.

2018-11-16 02:21 UTC, eyeballss commented on run_hadoop
> +        echo "Overlay network is my-net, 0 for creating master container but 1, slave from 1, slave to 5"
한글로 작성할께요..

2018-11-16 06:41 UTC, sungsu7437 commented
script에 
slaves 파일을 수정하는 것도 필요하다고 생각함 (입력하는 slave 갯수 만큼)

2018-11-17 08:27 UTC, hyu-leeky commented on Dockerfile
> +
삭제필요?

2018-11-17 08:28 UTC, kmu-leeky commented on run_hadoop
> +        echo "./run_hadoop [network-name] [want-master] [slave-from] [slave-to]"
want_master 가 0일때 안만드는건 이상하지 않아? 1일때 만드는게 맞지 않을까?
설명듣고보니 지난번에 그렇게 했던것 같아. 다른 좋은 방법이 있으면 수정하고, 아니면 지금도 나쁘지는 않을듯.

2018-11-17 08:31 UTC, kmu-leeky commented
> script에
> slaves 파일을 수정하는 것도 필요하다고 생각함 (입력하는 slave 갯수 만큼)

성수 good comment. @eyeballss 같이 챙겨줘.

2018-11-19 10:51 UTC, eyeballss reviewed
교수님 오늘 말씀해주신거 잘 이해했는지 확인 좀 부탁드립니다.
서버가 총 3대 있고 ( bd1, bd2, bd3 )
각각의 서버마다 50g 메모리가 있다고 가정합니다.
사용자가 bd1에 7개 컨테이너,
bd2에 7개 컨테이너,
bd3에 6개 컨테이너를 만들고 싶어 할 때
bd1에서는 50/7 = 7.xx 이니까 각 컨테이너 당 7g씩 주면 되고
bd2에서도 각 컨테이너 당 7g씩 주면 되고
bd3에서는 50/6 = 8.xx 이니까 각 컨테이너 당 8g씩 주면 된다
...고 이해했는데 잘 이해한게 맞나요?

2018-11-19 10:51 UTC, eyeballss commented on run_hadoop
>  numOfContainers=1
아 그렇네요 맞습니다.

2018-11-19 11:19 UTC, kmu-leeky commented
@eyeballss 너무 복잡한 시나리오는 만들지 말고, 메모리는 전체 서버에 같은 양을 하드코딩, 그리고 컨테니너 갯수는 각 서버당 같게끔 하자. 예를들어 6으로 하면, bd-1, bd-2, bd-3 모두 6개 컨테이너 해서 토탈은 18개로.

2018-11-19 11:20 UTC, eyeballss commented
네 교수님 알겠습니다

2018-11-19 15:22 UTC, eyeballss commented
이해한 게 맞는지 몰라서 run_hadoop 을 두 가지 버전으로 만들어 보았습니다 ㅠㅠ;;
피드백 부탁드립니다..
그리고 Dockerfile에서 slaves 넣는 부분을 지웠고 대신 change_slaves 라는 shell script 를 통해 master container 내에서 workers 파일 (hadoop v3 에서의 slaves 파일) 내에 slaves 의 이름을 넣도록 했습니다.

2018-11-19 23:51 UTC, kmu-leeky commented on Dockerfile
> +
@eyeballss 아래 라인 필요없으면 삭제하자.

2018-11-19 23:54 UTC, eyeballss commented on Dockerfile
> +
어? 저게 뭐지;; 복붙하다가 붙었나봅니다. 바로 삭제할께요

2018-11-19 23:57 UTC, hyu-leeky requested changes
v1 이 충분할것 같은데?

2018-11-19 23:57 UTC, kmu-leeky commented on change_slaves
> +        echo "파라미터가 없습니다."
파라미터가 어떤걸 포함해야 하는지도 추가로 메시지로 보여주면 좋을듯. 사용법 설명.

2018-11-19 23:57 UTC, kmu-leeky commented on change_slaves
> +WORKERS_FILE="/usr/local/hadoop/etc/hadoop/workers"
이제는 파일 이름이 slaves 가 아니라 workers 인거야?
그리고 가능하면 경로의 경우 /usr/local/hadoop/ 보다는 $HADOOP_HOME 이라는 변수를 사용하는게 추후에 홈폴더 변경시에 작업하기에 더 좋을거야.

2018-11-19 23:57 UTC, kmu-leeky commented on run_hadoop_v1
> +CONTAINER_MEMORY=`expr $SERVER_MEMORY / $NUM_OF_CONTAINERS`g
nice!

2018-11-19 23:57 UTC, kmu-leeky commented on run_hadoop_v1
> +RANDOM_NUM=`expr $RANDOM % 10000 + 30000`
nice.

2018-11-20 00:54 UTC, eyeballss commented on run_hadoop
> +
< 로 바꿨습니다.( 코드 상에 -lt )

2018-11-20 01:17 UTC, hyu-leeky requested changes
거의 다 된듯 하다.

2018-11-20 01:17 UTC, kmu-leeky commented on run_hadoop
> +NUM_OF_CONTAINERS=`expr $2 + $4 - $3 + 1`
comment 를 달아줄래? 어떻게 계산이 되는건지? $2 를 포함 하는 걸 보면 마스터 컨테이너도 포함하는것 같은데, 그렇게 되면 메모리 분배가 딱 떨어지지 않을것 같은 생각이 들어서.. 혹시 마스터는 전체 컨테이너 개수에서 빼면 어떨까?
마스터는 여유있게 많이 자원을 할당하는 걸로..

그리고 아래에도 보면 계쏙 $1, $2, 이렇게 사용하는데, 이렇게 되면 사용자가 입력 인자의 순서를 계속적으로 확인을 해야해서 가독성이 떨어질것 같아.
MASTER_CREATE=$2
CONTAINER_START_INDEX=$3
CONTAINER_END_INDEX=$4

이런식으로 해서 변수화 하는것도 좋을것 같아.

2018-11-20 01:17 UTC, kmu-leeky commented on run_hadoop
> +SLAVE_OPTION="--cpu-shares 1024 --memory $CONTAINER_MEMORY --storage-opt size=300G "
storage-opt-size 의 경우 일단은 변수를 만들어 두고 변수에 값을 넣은 후에 변수를 사용하는걸로 하자.그게 더 읽기가 좋을듯.

2018-11-20 01:17 UTC, kmu-leeky commented on change_slaves
> +#! /bin/bash
이 파일이 change_slaves 라고 하니까 이름이 조금 어색해 보이네.
make_workers_file 이렇게 하면 어떨까?

2018-11-20 02:15 UTC, eyeballss commented on run_hadoop
> +NUM_OF_CONTAINERS=`expr $2 + $4 - $3 + 1`
네 변수화해서 사용할께요

2018-11-20 02:29 UTC, eyeballss commented on run_hadoop
> +NUM_OF_CONTAINERS=`expr $2 + $4 - $3 + 1`
하나의 서버에 50g 의 메모리를 갖고 있다는 가정을 합니다.
$2+$4-$3+1의 값은 앞으로 만들 마스터와 슬레이브 컨테이너의 개수(NUM_OF_CONTAINERS)가 되는데, 
이 개수로 50을 나눈 값(50/NUM_OF_CONTAINERS)이 각 컨테이너에 할당되는 메모리 크기가 됩니다.

교수님께서 말씀하신 대로 $2(마스터)를 계산식에서 제외하면 slaves containers 수로만 계산이 될 것입니다. master에게는 30g 의 메모리를 넣는 것으로 할께요.

결과적으로, master, slave1, 2, 3을 만든다고 할 때 master 30 g, 각 slaves에 16g씩 메모리가 할당되게 됩니다.

2018-11-20 02:32 UTC, eyeballss commented on change_slaves
> +#! /bin/bash
네 이름 바꾸겠습니다

2018-11-20 02:33 UTC, kmu-leeky commented on run_hadoop
> +NUM_OF_CONTAINERS=`expr $2 + $4 - $3 + 1`
응 마스터에 기본적으로 할당되는 메모리 양은 변수로 만들어 두고 워커에 관련한 메모리만 할당해주는 방향으로 작성을 해보자.

2018-11-20 03:19 UTC, eyeballss commented on run_hadoop
> +SLAVE_OPTION="--cpu-shares 1024 --memory $CONTAINER_MEMORY --storage-opt size=300G "
변수에 넣어 사용하도록 업데이트 했습니다.

2018-11-20 03:20 UTC, eyeballss commented on run_hadoop
> +NUM_OF_CONTAINERS=`expr $2 + $4 - $3 + 1`
네 master에는 30이라는 고정된 값이 들어가고, 나머지 slaves 에는 50을 slaves 개수로 나눈 값을 메모리 크기로 넣도록 만들었습니다.

2018-11-20 07:29 UTC, eyeballss commented
git에 올라와있는 코드를 bd1, bd3 에서 clone 하여 hdfs mapreduce 돌려 본 결과 문제 없이 잘 되는 것을 확인했습니다. 명령어도 잘 만들어지고, 컨테이너도 잘 생성되고, make_workers_file 스크립트를 사용하여 workers 파일 업데이트도 제대로 됩니다.

bd1, bd3 에서 run_hadoop을 실행시킬 때는 메모리 옵션은 제외하였습니다. 포함시킨상태로 실행하니 아래 에러가 뜹니다.

leecw@bd-1:~/ubuntu-hadoop$ ./run_hadoop cwl-test-net 1 1 2
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
8f4eec94e16ed77b3bee74191188537becb2e8bb27a244aa4b6c7f21dcfe5783
docker: Error response from daemon: Error mounting '/dev/mapper/docker-8:16-195297289-f22d71769036d9347b07eef998dcb84c8bd6375c86193c0ddb3763a2953d5fd5-init' on '/run/docker/mnt' (fstype='xfs' options='nouuid'): invalid argument
<6>[1028909.290736] docker_gwbridge: port 2(vethef796eb) entered forwarding state
<6>[1028909.290745] docker_gwbridge: port 2(vethef796eb) entered forwarding state
<4>[1028909.590805] XFS (dm-5): Invalid superblock magic number.
See 'docker run --help'.
docker: Error response from daemon: Error mounting '/dev/mapper/docker-8:16-195297289-5e58c00da1cd414f0196c16efa61871f1009566a146df9342942dba61282e07b-init' on '/run/docker/mnt' (fstype='xfs' options='nouuid'): invalid argument
<6>[1028909.290745] docker_gwbridge: port 2(vethef796eb) entered forwarding state
<4>[1028909.590805] XFS (dm-5): Invalid superblock magic number
<4>[1028909.863551] XFS (dm-5): Invalid superblock magic number.
See 'docker run --help'.

또 bd 서버에서 clone 한 run_hadoop 이나 make_workers_file 내용을 보면 한글이 깨져있습니다.

2018-11-20 08:53 UTC, kmu-leeky commented on make_workers_file
> +        echo "./change_slaves [만든 slave 컨테이너의 첫 범위] [만든 slave 컨테이너의 마지막 범위]"
여기 이름도 수정 make_workers_file 로. 아래 도 마찬가지.

2018-11-20 08:53 UTC, kmu-leeky commented on run_hadoop
> +MASTER_CONTAINER_MEMORY="30g"
조금 줄이면 어떨까? 10g 정도?

2018-11-20 08:53 UTC, kmu-leeky commented on make_workers_file
> +#! /bin/bash
그런데 이파일은 따로 불러줘야 하는거야?
run_hadoop 에서 master container 를 만들도록 했으면 불러줘야 할것 같은데.
이게 호출되는 시점을 확인해줄래?

2018-11-20 08:56 UTC, kmu-leeky commented
> git에 올라와있는 코드를 bd1, bd3 에서 clone 하여 hdfs mapreduce 돌려 본 결과 문제 없이 잘 되는 것을 확인했습니다. 명령어도 잘 만들어지고, 컨테이너도 잘 생성되고, make_workers_file 스크립트를 사용하여 workers 파일 업데이트도 제대로 됩니다.
> 
> bd1, bd3 에서 run_hadoop을 실행시킬 때는 메모리 옵션은 제외하였습니다. 포함시킨상태로 실행하니 아래 에러가 뜹니다.
> 
> leecw@bd-1:~/ubuntu-hadoop$ ./run_hadoop cwl-test-net 1 1 2
> WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
> 8f4eec94e16ed77b3bee74191188537becb2e8bb27a244aa4b6c7f21dcfe5783
> docker: Error response from daemon: Error mounting '/dev/mapper/docker-8:16-195297289-f22d71769036d9347b07eef998dcb84c8bd6375c86193c0ddb3763a2953d5fd5-init' on '/run/docker/mnt' (fstype='xfs' options='nouuid'): invalid argument
> <6>[1028909.290736] docker_gwbridge: port 2(vethef796eb) entered forwarding state
> <6>[1028909.290745] docker_gwbridge: port 2(vethef796eb) entered forwarding state
> <4>[1028909.590805] XFS (dm-5): Invalid superblock magic number.
> See 'docker run --help'.
> docker: Error response from daemon: Error mounting '/dev/mapper/docker-8:16-195297289-5e58c00da1cd414f0196c16efa61871f1009566a146df9342942dba61282e07b-init' on '/run/docker/mnt' (fstype='xfs' options='nouuid'): invalid argument
> <6>[1028909.290745] docker_gwbridge: port 2(vethef796eb) entered forwarding state
> <4>[1028909.590805] XFS (dm-5): Invalid superblock magic number
> <4>[1028909.863551] XFS (dm-5): Invalid superblock magic number.
> See 'docker run --help'.
> 
> 또 bd 서버에서 clone 한 run_hadoop 이나 make_workers_file 내용을 보면 한글이 깨져있습니다.

이 에러는 memory 옵션이 아니라, storage option 때문일것 같은데...
storage option 을 확인해줄래? @sungsu7437  랑 봤을때 storage 옵션을 주었을대 이런 에러가 발생했어.
그리고 docker 의 파일 시스템을 overlay2 로 업데이트 하는 작업을 해야 하고.

2018-11-21 04:22 UTC, eyeballss commented on make_workers_file
> +#! /bin/bash
교수님 말씀대로 하기 위해선, run_hadoop으로 master container를 만들 때 make_workers_file을 실행시켜야 하는데, 그 시점에서 사용자가 다른 서버(예를 들면 bd2, bd3)에 몇 개의 slaves를 만들었는지 알고 있어야 합니다. 

예를 들면, bd1에서 run_hadoop으로 master를 만들 때 "slaves를 총 10개 만들겠다" 고 이미 알고 있어야 하고 또 그 값(10)을 파라미터로 받는다면 master container 내의 workers 파일에 slave1,2,..10 을 넣을 수 있습니다. 대신 bd2 , bd3 에 run_hadoop으로 추가적으로 만드는 slaves container 개수는 총 10개를 넘지 않아야 합니다.

파라미터로 받도록 만들까요?

2018-11-21 04:29 UTC, eyeballss commented
교수님 run_hadoop_v1 이라는 이름으로 임시 파일을 하나 만들어봤습니다.

바뀐 내용은 아래와 같습니다.
교수님께서 말씀하신 대로 run_hadoop 내에서 master를 만들 때 make_workers_file 을 실행합니다.
파라미터값($5)으로 전 서버에 걸쳐 총 slaves 개수를 받고 그걸 토대로 slave1 2.. $5 까지의 slave 이름 리스트를 master의 workers 내용으로 넣습니다.
또한, master memory size를 10으로 바꾸었습니다.
교수님께서 마스터 노드에 memory 널널하게 넣으라고 하신 게 기억나서, slaves 메모리 사이즈가 master 메모리 사이즈보다 커지지 않도록 master 메모리 사이즈로 제한을 둡니다.

2018-11-21 07:20 UTC, hyu-leeky approved these changes
nicely done.

지난번에 얘기했던 에러는 이제 더이상 발생하지 않는거야?
@sungsu7437 @KimJeongChul  리뷰 해줘.

2018-11-21 07:58 UTC, eyeballss commented
@sungsu7437 가 이제 overlay 에 대해 처리한다고 합니다.

2018-11-21 08:15 UTC, sungsu7437 commented
오늘안에 도커 관련 세팅 끝나고 다시 말씀드리겠습니다.

2018-11-25 19:27 UTC, hyu-leeky commented
@KimJeongChul @sungsu7437  코드 리뷰 해줘.
@eyeballss 는 코드 리뷰 통해서 approve 되면 관련있는 파일들만 남기고 master 로 push 해줘.
@eyeballss  한가지더 작업해야 하는게,
리포지토리 루트에 있는 README.md 파일에 run_hadoop 실행 방법을 작성해줘. 누구라도 쉽게 사용 가능하도록.

2018-11-27 23:34 UTC, hyu-leeky approved these changes
nice job!!

2018-11-28 01:16 UTC, merged